export interface BirthdayWish {
  age: number
  wish: string
  wishBn: string
  emoji: string
}

export const birthdayWishes: BirthdayWish[] = [
  { age: 0, wish: "Welcome to the world, little one! The adventure begins.", wishBn: "পৃথিবীতে স্বাগতম, ছোট্ট একটি! অ্যাডভেঞ্চার শুরু হয়েছে।", emoji: "👶" },
  { age: 1, wish: "First birthday! One year of pure love and joy.", wishBn: "প্রথম জন্মদিন! ভালোবাসা ও আনন্দে ভরা এক বছর।", emoji: "🎂" },
  { age: 2, wish: "Two years old! Walking, talking, and spreading smiles.", wishBn: "দুই বছর! হাঁটা, কথা বলা এবং হাসি ছড়ানো।", emoji: "👣" },
  { age: 3, wish: "Three and thriving! Every day is a new discovery.", wishBn: "তিন বছর বয়সী এবং বৃদ্ধি পাচ্ছে! প্রতিদিন নতুন আবিষ্কার।", emoji: "🌈" },
  { age: 4, wish: "Four years of magic. Keep shining, little star!", wishBn: "চার বছরের জাদু। জ্বলতে থাকো, ছোট্ট তারা!", emoji: "⭐" },
  { age: 5, wish: "Half a decade! Starting school adventures soon.", wishBn: "পাঁচ বছর! শীঘ্রই স্কুলের অ্যাডভেঞ্চার শুরু।", emoji: "🎒" },
  { age: 6, wish: "Six and curious! Learning something new every day.", wishBn: "ছয় বছর বয়সী এবং কৌতূহলী! প্রতিদিন নতুন কিছু শেখে।", emoji: "📚" },
  { age: 7, wish: "Lucky number seven! Making friends and memories.", wishBn: "ভাগ্যবান সংখ্যা সাত! বন্ধু ও স্মৃতি তৈরি করা।", emoji: "🍀" },
  { age: 8, wish: "Eight years strong! You're becoming amazing.", wishBn: "আট বছর শক্তিশালী! তুমি অসাধারণ হয়ে উঠছো।", emoji: "💪" },
  { age: 9, wish: "Nine and wonderful! Keep being your awesome self.", wishBn: "নয় বছর বয়সী এবং অসাধারণ! এভাবেই থেকো।", emoji: "🌟" },
  { age: 10, wish: "Double digits! A whole decade of being incredible.", wishBn: "দুই অঙ্কের বয়স! অসাধারণ থাকার একটি পূর্ণ দশক।", emoji: "🎉" },
  { age: 11, wish: "Eleven! The world is yours to explore.", wishBn: "এগারো বছর! পৃথিবী তোমার অনুসন্ধানের জন্য।", emoji: "🌍" },
  { age: 12, wish: "Almost a teenager! So much ahead of you.", wishBn: "প্রায় কিশোরী! তোমার সামনে অনেক কিছু আছে।", emoji: "🚀" },
  { age: 13, wish: "Thirteen! Welcome to your teenage years.", wishBn: "তেরো বছর! তোমার কিশোর বয়সে স্বাগতম।", emoji: "🎈" },
  { age: 14, wish: "Fourteen and fearless! Dream big, little one.", wishBn: "চৌদ্দ বছর বয়সী এবং নির্ভীক! বড় স্বপ্ন দেখো।", emoji: "🦋" },
  { age: 15, wish: "Fifteen! Halfway to thirty. Keep blooming.", wishBn: "পনেরো বছর! ত্রিশের অর্ধেক। ফোটে থাকো।", emoji: "🌸" },
  { age: 16, wish: "Sweet sixteen! A year of new beginnings.", wishBn: "ষোল বছর! নতুন শুরুর এক বছর।", emoji: "💖" },
  { age: 17, wish: "Seventeen! Almost there. Stay shining.", wishBn: "সতেরো বছর! প্রায় পৌঁছে গেছো। জ্বলতে থাকো।", emoji: "✨" },
  { age: 18, wish: "Eighteen! Officially an adult. The world awaits.", wishBn: "আঠারো বছর! আনুষ্ঠানিকভাবে প্রাপ্তবয়স্ক। পৃথিবী অপেক্ষা করছে।", emoji: "🔑" },
  { age: 19, wish: "Nineteen! So close to twenty. Treasure every moment.", wishBn: "উনিশ বছর! কুড়ির এত কাছে। প্রতিটি মুহূর্ত লালন করো।", emoji: "💫" },
  { age: 20, wish: "Happy 20th Birthday! Two decades of being amazing!", wishBn: "শুভ ২০তম জন্মদিন! অসাধারণ থাকার দুই দশক!", emoji: "🎂" },
  { age: 21, wish: "Twenty-one! A new chapter begins. Embrace it all.", wishBn: "কুড়ি এক বছর! নতুন অধ্যায় শুরু হচ্ছে। সবকিছু গ্রহণ করো।", emoji: "📖" },
  { age: 22, wish: "Twenty-two! Keep chasing those dreams.", wishBn: "বাইশ বছর! সেই স্বপ্নগুলো তাড়াতে থাকো।", emoji: "🎯" },
  { age: 23, wish: "Twenty-three! You're writing your own story.", wishBn: "তেইশ বছর! তুমি নিজের গল্প লিখছো।", emoji: "✍️" },
  { age: 24, wish: "Twenty-four! Growing wiser and more beautiful.", wishBn: "চুব্বিশ বছর! আরও জ্ঞানী ও সুন্দর হয়ে উঠছো।", emoji: "🌱" },
  { age: 25, wish: "Quarter life and already so accomplished!", wishBn: "জীবনের এক-চতুর্থাংশ এবং ইতিমধ্যে এত সফল!", emoji: "🏅" },
  { age: 26, wish: "Twenty-six! The best is yet to come.", wishBn: "ছব্বিশ বছর! সেরাটি এখনো আসেনি।", emoji: "🌅" },
  { age: 27, wish: "Twenty-seven! Living your best life.", wishBn: "সাতাশ বছর! তোমার সেরা জীবন কাটাচ্ছো।", emoji: "💃" },
  { age: 28, wish: "Twenty-eight! Confidence looks good on you.", wishBn: "আঠাশ বছর! আত্মবিশ্বাস তোমার উপর সুন্দর দেখায়।", emoji: "💎" },
  { age: 29, wish: "Twenty-nine! Last year of your twenties. Make it count.", wishBn: "ঊনত্রিশ বছর! তোমার কুড়ির শেষ বছর। গুরুত্বপূর্ণ করো।", emoji: "🔥" },
  { age: 30, wish: "Thirty and fabulous! A new decade of possibilities.", wishBn: "ত্রিশ বছর এবং অসাধারণ! সম্ভাবনার নতুন দশক।", emoji: "🥂" },
  { age: 31, wish: "Thirty-one! Wiser, stronger, more you.", wishBn: "একত্রিশ বছর! আরও জ্ঞানী, শক্তিশালী, আরও তুমি।", emoji: "💪" },
  { age: 32, wish: "Thirty-two! Still growing, still glowing.", wishBn: "বত্রিশ বছর! এখনো বৃদ্ধি পাচ্ছো, এখনো জ্বলছো।", emoji: "✨" },
  { age: 33, wish: "Thirty-three! Triple the the blessings.", wishBn: "তেত্রিশ বছর! তিনগুণ আশীর্বাদ।", emoji: "🙏" },
  { age: 34, wish: "Thirty-four! Every year better than the last.", wishBn: "চৌত্রিশ বছর! প্রতিটি বছর আগের চেয়ে ভালো।", emoji: "📈" },
  { age: 35, wish: "Thirty-five! Peak of your prime years.", wishBn: "পৈঁত্রিশ বছর! তোমার সেরা বছরের চূড়ায়।", emoji: "🏔️" },
  { age: 36, wish: "Thirty-six! Keep shining brighter than ever.", wishBn: "ছত্রিশ বছর! আগের চেয়ে উজ্জ্বল জ্বলতে থাকো।", emoji: "☀️" },
  { age: 37, wish: "Thirty-seven! Your glow is unmatched.", wishBn: "সাইত্রিশ বছর! তোমার ঝলকানি অমীমাংসিত।", emoji: "👑" },
  { age: 38, wish: "Thirty-eight! Still the queen of every room.", wishBn: "আড়ত্রিশ বছর! এখনো প্রতিটি ঘরের রানী।", emoji: "👸" },
  { age: 39, wish: "Thirty-nine! The best is always ahead.", wishBn: "ঊনচল্লিশ বছর! সেরাটি সবসময় সামনে।", emoji: "🔮" },
  { age: 40, wish: "Forty and thriving! Life begins at 40.", wishBn: "চল্লিশ বছর এবং বৃদ্ধি পাচ্ছো! জীবন ৪০-তে শুরু হয়।", emoji: "🎊" },
  { age: 41, wish: "Forty-one! Still going strong.", wishBn: "একচল্লিশ বছর! এখনো শক্তিশালী।", emoji: "💪" },
  { age: 42, wish: "Forty-two! A masterpiece in progress.", wishBn: "বিয়াল্লিশ বছর! চলমান একটি শিল্পকর্ম।", emoji: "🎨" },
  { age: 43, wish: "Forty-three! Gracefully owning every year.", wishBn: "তেতাল্লিশ বছর! সুন্দরভাবে প্রতিটি বছরের মালিক।", emoji: "🌹" },
  { age: 44, wish: "Forty-four! More to give, more to receive.", wishBn: "চুয়াল্লিশ বছর! দেওয়ার আরও কিছু, পাওয়ার আরও কিছু।", emoji: "🎁" },
  { age: 45, wish: "Forty-five! Halfway to ninety. What a journey!", wishBn: "পঁয়তাল্লিশ বছর! নব্বই-এর অর্ধেক। যাত্রাটা দারুণ!", emoji: "🗺️" },
  { age: 46, wish: "Forty-six! Still writing beautiful chapters.", wishBn: "ছেচল্লিশ বছর! এখনো সুন্দর অধ্যায় লিখছো।", emoji: "📝" },
  { age: 47, wish: "Forty-seven! Wisdom and beauty combined.", wishBn: "সাতচল্লিশ বছর! জ্ঞান ও সৌন্দর্যের সমন্বয়।", emoji: "🎓" },
  { age: 48, wish: "Forty-eight! Still the life of the party.", wishBn: "আড়তাল্লিশ বছর! এখনো অনুষ্ঠানের প্রাণ।", emoji: "🎪" },
  { age: 49, wish: "Forty-nine! One year away from fifty.", wishBn: "ঊনপঞ্চাশ বছর! পঞ্চাশের এক বছর দূরে।", emoji: "⏳" },
  { age: 50, wish: "Fifty and fabulous! Half a century of greatness.", wishBn: "পঞ্চাশ বছর এবং অসাধারণ! মহানতার অর্ধেক শতাব্দী।", emoji: "🏆" },
  { age: 51, wish: "Fifty-one! The legend continues.", wishBn: "একান্ন বছর! কিংবদন্তী চলছে।", emoji: "📖" },
  { age: 52, wish: "Fifty-two! More blessings than ever.", wishBn: "বায়ান্ন বছর! আগের চেয়ে বেশি আশীর্বাদ।", emoji: "🙏" },
  { age: 53, wish: "Fifty-three! Still turning heads.", wishBn: "তিপান্ন বছর! এখনো মাথা ঘুরিয়ে দেয়।", emoji: "😍" },
  { age: 54, wish: "Fifty-four! Aging like fine wine.", wishBn: "চুয়ান্ন বছর! ভালো ওয়াইনের মতো বয়স্ক হচ্ছো।", emoji: "🍷" },
  { age: 55, wish: "Fifty-five! A true icon.", wishBn: "পঞ্চান্ন বছর! একজন প্রকৃত আইকন।", emoji: "🌟" },
  { age: 56, wish: "Fifty-six! Still the star of the show.", wishBn: "ছাপ্পান্ন বছর! এখনো অনুষ্ঠানের তারকা।", emoji: "⭐" },
  { age: 57, wish: "Fifty-seven! Living proof that age is just a number.", wishBn: "সাতান্ন বছর! বয়স শুধু একটি সংখ্যা তার প্রমাণ।", emoji: "🔢" },
  { age: 58, wish: "Fifty-eight! Stronger with every year.", wishBn: "আটান্ন বছর! প্রতিটি বছর আরও শক্তিশালী।", emoji: "💪" },
  { age: 59, wish: "Fifty-nine! The best years keep coming.", wishBn: "ঊনষাট বছর! সেরা বছরগুলো আসতে থাকছে।", emoji: "🌅" },
  { age: 60, wish: "Sixty! A diamond jubilee of life!", wishBn: "ষাট বছর! জীবনের হীরক জয়ন্তী!", emoji: "💎" },
  { age: 61, wish: "Sixty-one! Still shining bright.", wishBn: "একষটি বছর! এখনো উজ্জ্বল।", emoji: "☀️" },
  { age: 62, wish: "Sixty-two! Grace in every step.", wishBn: "বাষট্টি বছর! প্রতিটি পদক্ষেপে কৃপা।", emoji: "🦢" },
  { age: 63, wish: "Sixty-three! Still the heartbeat of the family.", wishBn: "তিরষটি বছর! এখনো পরিবারের হৃদয়স্পন্দন।", emoji: "❤️" },
  { age: 64, wish: "Sixty-four! More laughter, more love.", wishBn: "চৌষটি বছর! আরও হাসি, আরও ভালোবাসা।", emoji: "😄" },
  { age: 65, wish: "Sixty-five! Retirement? Never heard of it.", wishBn: "পঁয়ষটি বছর! অবসর? কখনো শোনেনি।", emoji: "🏖️" },
  { age: 66, wish: "Six-six! Still running the show.", wishBn: "ষাট ছয় বছর! এখনো দল চালাচ্ছে।", emoji: "🎪" },
  { age: 67, wish: "Sixty-seven! A living treasure.", wishBn: "সাতষটি বছর! একটি জীবন্ত সম্পদ।", emoji: "💰" },
  { age: 68, wish: "Sixty-eight! Your smile lights up the world.", wishBn: "আটষটি বছর! তোমার হাসি পৃথিবী আলোকিত করে।", emoji: "😊" },
  { age: 69, wish: "Sixty-nine! Almost a septuagenarian legend.", wishBn: "ঊনসত্তর বছর! প্রায় সপ্তাশীতি কিংবদন্তী।", emoji: "🏅" },
  { age: 70, wish: "Seventy! A lifetime of love and wisdom.", wishBn: "সত্তর বছর! ভালোবাসা ও জ্ঞানের একটি পূর্ণ জীবন।", emoji: "🕊️" },
  { age: 71, wish: "Seventy-one! Still breaking barriers.", wishBn: "একাত্তর বছর! এখনো বাধা ভাঙছে।", emoji: "🚧" },
  { age: 72, wish: "Seventy-two! A true blessing to know you.", wishBn: "বাহাত্তর বছর! তোমাকে চেনা একটি প্রকৃত আশীর্বাদ।", emoji: "🙏" },
  { age: 73, wish: "Seventy-three! Still young at heart.", wishBn: "তিয়াত্তর বছর! হৃদয়ে এখনো তরুণ।", emoji: "💗" },
  { age: 74, wish: "Seventy-four! The family's guiding light.", wishBn: "চুয়াত্তর বছর! পরিবারের পথপ্রদর্শক।", emoji: "🕯️" },
  { age: 75, wish: "Seventy-five! A diamond year of pure joy.", wishBn: "পঁয়ত্তর বছর! বিশুদ্ধ আনন্দের হীরক বছর।", emoji: "💎" },
  { age: 76, wish: "Seventy-six! Still making history.", wishBn: "ছিয়াত্তর বছর! এখনো ইতিহাস তৈরি করছে।", emoji: "📜" },
  { age: 77, wish: "Seventy-seven! Lucky in every way.", wishBn: "সাতাশ্বের বছর! প্রতিটি দিক থেকে ভাগ্যবান।", emoji: "🍀" },
  { age: 78, wish: "Seventy-eight! Still the heart of the party.", wishBn: "আটাশ্বের বছর! এখনো অনুষ্ঠানের হৃদয়।", emoji: "💝" },
  { age: 79, wish: "Seventy-nine! One more year to eighty!", wishBn: "ঊনআশি বছর! আশির জন্য আরেক বছর!", emoji: "🎯" },
  { age: 80, wish: "Eighty! An octogenarian icon!", wishBn: "আশি বছর! একজন অষ্টাশীতি আইকন!", emoji: "👑" },
  { age: 81, wish: "Eighty-one! Still going strong.", wishBn: "একাশি বছর! এখনো শক্তিশালী।", emoji: "💪" },
  { age: 82, wish: "Eighty-two! A masterpiece of life.", wishBn: "বিরাশি বছর! জীবনের একটি শিল্পকর্ম।", emoji: "🎨" },
  { age: 83, wish: "Eighty-three! Still painting the world beautiful.", wishBn: "তিরাশি বছর! এখনো পৃথিবীকে সুন্দর করছে।", emoji: "🖌️" },
  { age: 84, wish: "Eighty-four! A beacon of wisdom.", wishBn: "চুরাশি বছর! জ্ঞানের একটি বাতিঘর।", emoji: "🚦" },
  { age: 85, wish: "Eighty-five! A living legend indeed.", wishBn: "পঁচাশি বছর! সত্যিই একজন জীবন্ত কিংবদন্তী।", emoji: "🏅" },
  { age: 86, wish: "Eighty-six! Still the wisest in the room.", wishBn: "ছিয়াশি বছর! এখনো ঘরের সবচেয়ে জ্ঞানী।", emoji: "🧠" },
  { age: 87, wish: "Eighty-seven! Your love is timeless.", wishBn: "সাতাশি বছর! তোমার ভালোবাসা কালোদিত।", emoji: "💖" },
  { age: 88, wish: "Eighty-eight! Double infinity of blessings.", wishBn: "আটাশি বছর! আশীর্বাদের দ্বি-অসীমতা।", emoji: "♾️" },
  { age: 89, wish: "Eighty-nine! Almost ninety. What a ride!", wishBn: "ঊননব্বই বছর! প্রায় নব্বই। যাত্রাটা দারুণ!", emoji: "🎢" },
  { age: 90, wish: "Ninety! A nonagenarian superstar!", wishBn: "নব্বই বছর! একজন নব্বই বছরের সুপারস্টার!", emoji: "🌟" },
  { age: 91, wish: "Ninety-one! Still the brightest star.", wishBn: "একান্ন বছর! এখনো সবচেয়ে উজ্জ্বল তারা।", emoji: "⭐" },
  { age: 92, wish: "Ninety-two! A treasure beyond measure.", wishBn: "বিরান্ন বছর! মাপার বাইরে একটি সম্পদ।", emoji: "💎" },
  { age: 93, wish: "Ninety-three! Still writing your story.", wishBn: "তিরান্ন বছর! এখনো তোমার গল্প লিখছো।", emoji: "✍️" },
  { age: 94, wish: "Ninety-four! Pure grace and wisdom.", wishBn: "চুরান্ন বছর! বিশুদ্ধ কৃপা ও জ্ঞান।", emoji: "🕊️" },
  { age: 95, wish: "Ninety-five! Halfway to a hundred!", wishBn: "পঁচান্ন বছর! শতের অর্ধেক!", emoji: "🎯" },
  { age: 96, wish: "Ninety-six! Still the family's treasure.", wishBn: "ছিয়ান্ন বছর! এখনো পরিবারের সম্পদ।", emoji: "💰" },
  { age: 97, wish: "Ninety-seven! A century awaits.", wishBn: "সাতান্ন বছর! শতাব্দী অপেক্ষা করছে।", emoji: "⏳" },
  { age: 98, wish: "Ninety-eight! Almost a century of love.", wishBn: "আটান্ন বছর! ভালোবাসার প্রায় শতাব্দী।", emoji: "💯" },
  { age: 99, wish: "Ninety-nine! One more year to the big one!", wishBn: "ঊনশো বছর! বড় শতাব্দীর জন্য আরেক বছর!", emoji: "🎈" },
  { age: 100, wish: "ONE HUNDRED! A century of incredible life. You made it!", wishBn: "একশো বছর! অসাধারণ জীবনের একটি শতাব্দী। তুমি পৌঁছে গেছো!", emoji: "💯" },
]
